language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
  - 1.7
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
  - 21.0
env:
  - MIX_ENV=test
script:
  - mix test
  - if [[ `elixir -v` = *"1.7"* ]]; then mix format --check-formatted; fi
after_success:
  - mix coveralls.travis
  - MIX_ENV=docs mix deps.get
branches:
  only:
    - master
cache:
  directories:
    - _build
    - deps
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
