language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6
  - 1.7.3
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
  - 21.0
env:
  - MIX_ENV=test
script:
  - mix test
after_success:
  - mix coveralls.travis
  - MIX_ENV=docs mix deps.get
branches:
  only:
    - master
